from django.urls import path
from .views import (
    IntersectionView,
    IntersectionCreateView,
    IntersectionEventUpdateView,
    IntersectionCarCreateView,
    IntersectionCarView,
    IntersectionClassificationView,
    IntersectionClassificationDetailView
)

urlpatterns = [
    path(
        "intersections/<int:intersection_id>/",
        IntersectionView.as_view(),
        name="intersection-detail",
    ),
    path(
        "intersections/create/",
        IntersectionCreateView.as_view(),
        name="intersection-create",
    ),
    path(
        "intersections/<str:intersection_id>/events/",
        IntersectionEventUpdateView.as_view(),
        name="intersection-event-update",
    ),
    path(
        "intersections/<int:intersection_id>/cars/",
        IntersectionCarCreateView.as_view(),
        name="intersection-cars",
    ),
    path(
        "intersections/<int:intersection_id>/cars/1/",
        IntersectionCarView.as_view(),
        name="intersection-car-detail",
    ),
    path(
        "intersections/<int:intersection_id>/cars/2/",
        IntersectionCarView.as_view(),
        name="intersection-car-detail-2",
    ),
    path(
        "intersections/<int:intersection_id>/classifications/",
        IntersectionClassificationView.as_view(),
        name="intersection-classifications",
    ),
    path(
        "intersections/<int:intersection_id>/classifications/<str:classification>/<int:modifier>/",
        IntersectionClassificationDetailView.as_view(),
        name="intersection-classification-detail",
    ),
    path(
        "intersections/<int:intersection_id>/classifications/<str:classification>/<int:modifier>/",
        IntersectionClassificationDetailView.as_view(),
        name="intersection-classification-detail-2",
    )
]
