# Generated by Django 5.0.6 on 2024-07-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Intersection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intersection_id", models.CharField(max_length=50, unique=True)),
                ("coordinates", models.CharField(max_length=100)),
                ("condition", models.CharField(default="Live", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Environmental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.FloatField(default=120)),
                ("vehicle_emissions", models.FloatField(default=0)),
                ("fuel_consumption", models.FloatField(default=0)),
                ("noise_pollution", models.FloatField(default=0)),
                ("air_quality_index", models.FloatField(default=0)),
                ("driving_conditions", models.FloatField(default=0)),
                ("fire_detection", models.FloatField(default=0)),
                (
                    "intersection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environmental_scores",
                        to="atlas_trafic_app.intersection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Efficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.FloatField(default=120)),
                ("congestion_level", models.FloatField(default=0)),
                ("average_traffic_speed", models.FloatField(default=0)),
                ("traffic_volume", models.FloatField(default=0)),
                ("signal_timing_efficiency", models.FloatField(default=0)),
                ("pedestrian_wait_time", models.FloatField(default=0)),
                ("micro_mobility_wait_time", models.FloatField(default=0)),
                (
                    "intersection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="efficiency_scores",
                        to="atlas_trafic_app.intersection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Safety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.FloatField(default=120)),
                ("accident_rate", models.FloatField(default=0)),
                ("near_misses", models.FloatField(default=0)),
                ("speeding", models.FloatField(default=0)),
                ("traffic_violations", models.FloatField(default=0)),
                ("pedestrian_incidents", models.FloatField(default=0)),
                ("damaged_disabled_vehicle", models.FloatField(default=0)),
                (
                    "intersection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_scores",
                        to="atlas_trafic_app.intersection",
                    ),
                ),
            ],
        ),
    ]
