# Generated by Django 5.0.6 on 2024-07-18 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas_trafic_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("Passenger Vehicle", "Passenger Vehicle"),
                            ("Heavy Truck", "Heavy Truck"),
                            ("Public Transportation", "Public Transportation"),
                            ("Pedestrian", "Pedestrian"),
                            ("Micromobility User", "Micromobility User"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("count", models.PositiveIntegerField(default=1)),
                (
                    "intersection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="atlas_trafic_app.intersection",
                    ),
                ),
            ],
        ),
    ]
