# Generated by Django 5.0.6 on 2024-07-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atlas_trafic_app", "0003_alter_car_count_alter_car_detected_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="detected_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
